services:
  - type: web
    name: flask-app
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000  # Render will set the actual port in the environment
